name: M@TE Model Request
description: Request a model to be included in the hub
title: "M@TE Model Request: <name>"
labels: [new-model]

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to open a Model Request!"

  - type: markdown
    attributes:
      value: "## About your model"

  - type: input
    id: title
    attributes:
      label: Title
      description: "Suggest a title for your model"
      placeholder: "Expanding Earth"
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: "Please provide an abstract for your model (preferrably plain language)"
      placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..."
    validations:
      required: true

  - type: textarea
    id: keywords
    attributes:
      label: Keywords
      description: "Please provide keywords"
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: dropdown
    id: for_codes
    attributes:
      label: Field of Research (FoR) Codes
      description: "Please add FoR Codes (see https://vocabs.ardc.edu.au/viewById/316)"
      multiple: true
      options:
        - "3706: Geophysics"
        - "370601: Applied geophysics"
        - "370602: Electrial and electromagnetic methods in geophysics"
        - "370603: Geodesy"
        - "370604: Geodynamics"
        - "370605: Geothermics and radiometrics"
        - "370606: Gravimetrics"
        - "370607: Magnetism and palaeomagnetism"
        - "370608: Petrophysics and rock mechanics"
        - "370609: Seismology and seismic exploration"
        - "370610: Geophysics not elsewhere defined"
    validations:
      required: true

  - type: checkboxes
    id: about_metadata_tags
    attributes:
      label: Metadata Tags
      description: "Select relevant boxes"
      options:
        - label: published study
        - label: community benchmark
        - label: attempted reproduction of a previous model (including with different codes, etc.)
        - label: missing data model (input files available, requires re-running by community)

  - type: markdown
    attributes:
      value: "## Model computation and reproduction

        ** Metadata Fields **

        The following fields provide information and references for sources and processes that were used to create the dataset.  Provide software and computing details, versioning, web references, DOIs, Github links, input datasets etc. on any of the components and workflows that went into the generation of the dataset."

  - type: input
    id: software_framework
    attributes:
      label: Software Framework
      placeholder: "e.g. UWGeodynamics"

  - type: input
    id: software_version
    attributes:
      label: Software Version
      placeholder: "e.g. models run with UWGeodynamics version 2.15, compatible with versions 2.12-2.15"

  - type: input
    id: source_code
    attributes:
      label: Source Code
      description: "Is code for the model available? If so, please provide link to repository (GitHub, GitLab, BitBucket...)?"

  - type: input
    id: input_datasets
    attributes:
      label: Input Datasets

  - type: input
    id: computer_details
    attributes:
      label: Computer Details
      description: "e.g. cluster name, operating system, MPI version, number of cores"

  - type: textarea
    id: computation_additional_notes
    attributes:
      label: Additional Notes
      placeholder: "E.g., This product was generated by XX method as described by XX et al. (yyyy) . Further details and code for the method are available in the Github/code repository XX....This product is derived from dataset XX (dataset doi or link to details). The method is detailed in .... and uses inputs X (link), Y (link), Z (link) to produce this published product."

  - type: checkboxes
    id: computation_metadata_tags
    attributes:
      label: Metadata Tags
      description: "Select relevant boxes"
      options:
        - label: this submission includes input files
        - label: this submission includes a software container or environent file for **running the model** (i.e. docker image, dockerfile, conda environment.yml)
        - label: this submission includes postprocessing files
        - label: this submission includes a software container or environent file **for postprocessing**
        - label: postprocessing files are linked to data on the NCI's GeoNetwork (through thredds/OPeNDAP API)

  - type: textarea
    id: computation_file_description
    attributes:
      label: File Description
      description: "Please describe any additional files (related to model execution, reproduction and postprocessing) in the table below"
      value:
        Filename/pattern | Description | Notes

        --- | --- | ---

        E.g., `model_files/input.py` (add rows as needed) | E.g., description of `model_files/input.py` |

        E.g., `model_files/Dockerfile` (add rows as needed) | E.g., description of `model_files/Dockerfile`  | E.g., link to existing image on Dockerhub

        E.g., `log.txt` | E.g., Logfile from original model execution on NCI Gadi  | 


  - type: markdown
    attributes:
      value: "## Model output data"

  - type: checkboxes
    id: output_metadata_tags
    attributes:
      label: Metadata Tags
      description: "Select relevant boxes"
      options:
        - label: this submission includes model output data

  - type: textarea
    id: dataset_summary
    attributes:
      label: Summary of Dataset
      description: "Pitch for the general user and not just the content expert. Helpful things would include: summary of the dataset, high-level description of the dataset contents, and why this dataset might be useful to experts and non-experts."

  - type: textarea
    id: output_additional_notes
    attributes:
      label: Additional Notes
      description: "Information and references for sources and processes that were used to create the dataset."

  - type: input
    id: temporal_extent
    attributes:
      label: Temporal Extents
      description: "e.g., Begin time (YYYY/MM/DD, or 50 Myr) End time (YYYY/MM/DD, or 20 Myr)"

  - type: input
    id: spatial_extent
    attributes:
      label: Spatial Extents
      description: "e.g., west bounding longitude (degrees), east bounding longitude (degrees), ..."

  - type: textarea
    id: output_file_description
    attributes:
      label: File Description
      description: "Model output data is _not_ submitted through Github. However the File Description Table provides a place to describe those files. Include anything that might be useful for the community (or your future self): datum or reference values, units, nature of the data (scalar/vector/tensor), order of components."
      value:
        Filename/pattern | Description | Notes

        --- | --- | ---

        E.g. `velocity_**.h5`, | E.g. velocity field on mesh nodes, units cm/y, first component is horizontal, second component is vertical (positive up), files saved at 1 Ma intervals  | 

        `topography.csv`  | E.g. topography relative to initial (undeformed) upper boundary of model, units m  | 



  - type: markdown
    attributes:
      value: "## Attribution"


  - type: input
    id: publication
    attributes:
      label: Associated Publication DOI

  - type: textarea
    id: funders
    attributes:
      label: Funder(s)
      description: "Please add rows as required if more than 1 funder."

  - type: textarea
    id: authors
    attributes:
      label: Author(s)

  - type: input
    id: model-license
    attributes:
      label: License
      description: "If there is a license, please provide the name of the license (or None if there is no license specified). Please check our [model repository](https://airtable.com/shrUcrUnd7jB9ChZV) to explore valid licenses."
      placeholder: "CC-BY-4.0"
    validations:
      required: true