name: M@TE Model Request
description: Request a model to be included in the hub
title: "M@TE Model Request: <name>"
labels: [new-model]

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to open a Model Request!"

  - type: markdown
    attributes:
      value: "## About your model"

  - type: input
    id: title
    attributes:
      label: Title
      description: "Suggest a title for your model"
      placeholder: "Expanding Earth"
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: "Please provide an abstract for your model (preferrably plain language)"
      placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..."
    validations:
      required: true

  - type: textarea
    id: keywords
    attributes:
      label: Keywords
      description: "Please provide keywords"
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: dropdown
    id: for_codes
    attributes:
      label: Field of Research (FoR) Codes
      description: "Please add FoR Codes (see https://vocabs.ardc.edu.au/viewById/316)"
      multiple: true
      options:
        - "3706: Geophysics"
        - "370601: Applied geophysics"
        - "370602: Electrial and electromagnetic methods in geophysics"
        - "370603: Geodesy"
        - "370604: Geodynamics"
        - "370605: Geothermics and radiometrics"
        - "370606: Gravimetrics"
        - "370607: Magnetism and palaeomagnetism"
        - "370608: Petrophysics and rock mechanics"
        - "370609: Seismology and seismic exploration"
        - "370610: Geophysics not elsewhere defined"
    validations:
      required: true

  - type: checkboxes
    id: about_metadata_tags
    attributes:
      label: Metadata Tags
      description: "Select relevant boxes"
      options:
        - label: published study
        - label: community benchmark
        - label: attempted reproduction of a previous model (including with different codes, etc.)
        - label: missing data model (input files available, requires re-running by community)

  - type: markdown
    attributes:
      value: "## Model computation and reproduction

        ** Metadata Fields **

        The following fields provide information and references for sources and processes that were used to create the dataset.  Provide software and computing details, versioning, web references, DOIs, Github links, input datasets etc. on any of the components and workflows that went into the generation of the dataset."

  - type: input
    id: software_framework
    attributes:
      label: Software Framework
      placeholder: "e.g. UWGeodynamics"
    validations:
      required: false

  - type: input
    id: software_version
    attributes:
      label: Software Version
      placeholder: "e.g. models run with UWGeodynamics version 2.15, compatible with versions 2.12-2.15"
    validations:
      required: false

  - type: input
    id: source_code
    attributes:
      label: Source Code
      description: "Is code for the model available? If so, please provide link to repository (GitHub, GitLab, BitBucket...)?"

  - type: input
    id: input_datasets
    attributes:
      label: Input Datasets

  - type: input
    id: computer_details
    attributes:
      label: Computer Details
      description: "e.g. cluster name, operating system, MPI version, number of cores"

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      placeholder: "E.g., This product was generated by XX method as described by XX et al. (yyyy) . Further details and code for the method are available in the Github/code repository XX....This product is derived from dataset XX (dataset doi or link to details). The method is detailed in .... and uses inputs X (link), Y (link), Z (link) to produce this published product."

  - type: checkboxes
    id: computation_metadata_tags
    attributes:
      label: Metadata Tags
      description: "Select relevant boxes"
      options:
        - label: this submission includes input files
        - label: this submission includes a software container or environent file for **running the model** (i.e. docker image, dockerfile, conda environment.yml)
        - label: this submission includes postprocessing files
        - label: this submission includes a software container or environent file **for postprocessing**
        - label: postprocessing files are linked to data on the NCI's GeoNetwork (through thredds/OPeNDAP API)

  - type: textarea
    id: file_description
    attributes:
      label: File Description
      description: "Please describe any additional files (related to model execution, reproduction and postprocessing) in the table below"
      value:
        Filename/pattern | Description | Notes
        --- | --- | ---
        E.g., `model_files/input.py` (add rows as needed) | E.g., description of `model_files/input.py` |
        E.g., `model_files/Dockerfile` (add rows as needed) | E.g., description of `model_files/Dockerfile`  | E.g., link to existing image on Dockerhub
        E.g., `log.txt` | E.g., Logfile from original model execution on NCI Gadi  | 
